//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun
    {
        public int id { get; set; }
        public string urunturu { get; set; }
        public string urunadi { get; set; }
        public Nullable<int> stokadeti { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    }
}
